name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  PACKAGE_OUPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - name: Pack
      run: dotnet pack src/PublicApi/PublicApi.csproj --configuration Release --no-restore --no-build --include-symbols --output ${{ env.PACKAGE_OUPUT_DIRECTORY }}
      
    - name: Add Source
      run: dotnet nuget add source --username ValiantsinSerada --password ${{ secrets.AUTH_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ValiantsinSerada/index.json"
      
    - name: Set API Key
      run: nuget setapikey ${{ secrets.AUTH_TOKEN }} -Source https://nuget.pkg.github.com/ValiantsinSerada/index.json
      
    - name: Push
      run: dotnet nuget push "/home/runner/work/eShop/eShopoutput/*.nupkg" -k ${{ secrets.AUTH_TOKEN }} -s https://nuget.pkg.github.com/ValiantsinSerada/index.json
